apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      protocol: TCP
      port: 1884
      targetPort: 1884
    - name: mqtt-secure
      protocol: TCP
      port: 8884
      targetPort: 8884
    - name: dashboard
      protocol: TCP
      port: 18083
      targetPort: 18083
  type: LoadBalancer
